/*
 * AbilitiesTab.java
 *
 * Created on June 26, 2008, 11:02 PM
 */

package pcgen.gui.tabs;

/**
 *
 * @author  Connor Petty <cpmeister@users.sourceforge.net>
 */
public class AbilitiesTab extends javax.swing.JPanel {
    
    /** Creates new form AbilitiesTab */
    public AbilitiesTab() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flippingSplitPane1 = new pcgen.gui.util.panes.FlippingSplitPane();
        jPanel1 = new javax.swing.JPanel();
        flippingSplitPane2 = new pcgen.gui.util.panes.FlippingSplitPane();
        infoPane1 = new pcgen.gui.tools.InfoPane();
        jPanel2 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        flippingSplitPane1.setDividerSize(7);
        flippingSplitPane1.setContinuousLayout(true);
        flippingSplitPane1.setOneTouchExpandable(true);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 205, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 280, Short.MAX_VALUE)
        );

        flippingSplitPane1.setLeftComponent(jPanel1);

        flippingSplitPane2.setDividerSize(7);
        flippingSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        flippingSplitPane2.setContinuousLayout(true);
        flippingSplitPane2.setOneTouchExpandable(true);

        infoPane1.setTitle("Feat Info");
        flippingSplitPane2.setTopComponent(infoPane1);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 184, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 160, Short.MAX_VALUE)
        );

        flippingSplitPane2.setRightComponent(jPanel2);

        flippingSplitPane1.setRightComponent(flippingSplitPane2);

        add(flippingSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pcgen.gui.util.panes.FlippingSplitPane flippingSplitPane1;
    private pcgen.gui.util.panes.FlippingSplitPane flippingSplitPane2;
    private pcgen.gui.tools.InfoPane infoPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    
}
