/*
 * ClassTab.java
 *
 * Created on June 26, 2008, 4:20 PM
 */

package pcgen.gui.tabs;

/**
 *
 * @author  Connor Petty <cpmeister@users.sourceforge.net>
 */
public class ClassTab extends javax.swing.JPanel {
    
    /** Creates new form ClassTab */
    public ClassTab() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        flippingSplitPane1 = new pcgen.gui.util.panes.FlippingSplitPane();
        flippingSplitPane2 = new pcgen.gui.util.panes.FlippingSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jTablePane1 = new pcgen.gui.util.JTablePane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        flippingSplitPane1.setDividerSize(7);
        flippingSplitPane1.setContinuousLayout(true);
        flippingSplitPane1.setOneTouchExpandable(true);

        flippingSplitPane2.setDividerSize(7);
        flippingSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        flippingSplitPane2.setContinuousLayout(true);
        flippingSplitPane2.setOneTouchExpandable(true);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButton1.setText("Add");
        jButton1.setDefaultCapable(false);
        jButton1.setMinimumSize(new java.awt.Dimension(100, 9));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 9));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jButton1, gridBagConstraints);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jSpinner1.setMinimumSize(new java.awt.Dimension(50, 18));
        jSpinner1.setPreferredSize(new java.awt.Dimension(50, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jSpinner1, gridBagConstraints);

        jButton2.setText("Remove");
        jButton2.setDefaultCapable(false);
        jButton2.setMinimumSize(new java.awt.Dimension(100, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jButton2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel1.add(jTablePane1, gridBagConstraints);

        flippingSplitPane2.setBottomComponent(jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Class Info", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jEditorPane1.setEditable(false);
        jScrollPane1.setViewportView(jEditorPane1);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        flippingSplitPane2.setTopComponent(jPanel3);

        flippingSplitPane1.setRightComponent(flippingSplitPane2);
        flippingSplitPane1.setLeftComponent(jPanel2);

        add(flippingSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pcgen.gui.util.panes.FlippingSplitPane flippingSplitPane1;
    private pcgen.gui.util.panes.FlippingSplitPane flippingSplitPane2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private pcgen.gui.util.JTablePane jTablePane1;
    // End of variables declaration//GEN-END:variables
    
}
