/*
 * SkillsTab.java
 *
 * Created on June 26, 2008, 8:49 PM
 */

package pcgen.gui.tabs;

/**
 *
 * @author  Connor Petty <cpmeister@users.sourceforge.net>
 */
public class SkillsTab extends javax.swing.JPanel {
    
    /** Creates new form SkillsTab */
    public SkillsTab() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flippingSplitPane1 = new pcgen.gui.util.panes.FlippingSplitPane();
        jPanel1 = new javax.swing.JPanel();
        flippingSplitPane2 = new pcgen.gui.util.panes.FlippingSplitPane();
        infoPane1 = new pcgen.gui.tools.InfoPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        flippingSplitPane1.setDividerSize(7);
        flippingSplitPane1.setContinuousLayout(true);
        flippingSplitPane1.setOneTouchExpandable(true);
        flippingSplitPane1.setLeftComponent(jPanel1);

        flippingSplitPane2.setDividerSize(7);
        flippingSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        flippingSplitPane2.setContinuousLayout(true);
        flippingSplitPane2.setOneTouchExpandable(true);

        infoPane1.setTitle("Skill Info");
        flippingSplitPane2.setTopComponent(infoPane1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {new Integer(1), null, null, null},
                {new Integer(2), null, null, null},
                {new Integer(3), null, null, null},
                {new Integer(4), null, null, null}
            },
            new String [] {
                "Level", "Class", "Skill Points", "Points Left"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);

        flippingSplitPane2.setRightComponent(jPanel2);

        flippingSplitPane1.setRightComponent(flippingSplitPane2);

        add(flippingSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pcgen.gui.util.panes.FlippingSplitPane flippingSplitPane1;
    private pcgen.gui.util.panes.FlippingSplitPane flippingSplitPane2;
    private pcgen.gui.tools.InfoPane infoPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
