/*
 * QueryFilterPanel.java
 *
 * Created on February 6, 2008, 9:36 PM
 */
package pcgen.gui.filter;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import pcgen.util.PropertyFactory;

/**
 * @author  Connor Petty <mistercpp2000@gmail.com>
 */
public class QuickFilterPanel extends javax.swing.JPanel
{

    private Sifter sifter;

    /** Creates new form QueryFilterPanel */
    public QuickFilterPanel(Sifter sifter)
    {
	initComponents();
	this.sifter = sifter;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        QueryField = new javax.swing.JTextField();
        ClearButton = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText(PropertyFactory.getString("InfoTabs.FilterLabel")); // NOI18N
        add(jLabel1);

        QueryField.getDocument().addDocumentListener(new DocumentListener(){
            public void insertUpdate(DocumentEvent e)
            {
                updateQueryFilter();
            }
            public void removeUpdate(DocumentEvent e)
            {
                updateQueryFilter();
            }
            public void changedUpdate(DocumentEvent e)
            {
                updateQueryFilter();
            }
        });
        add(QueryField);

        ClearButton.setText(PropertyFactory.getString("in_clear")); // NOI18N
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearQueryFilter(evt);
            }
        });
        add(ClearButton);
    }// </editor-fold>//GEN-END:initComponents
    private void clearQueryFilter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearQueryFilter
	clearQueryFilter();
}//GEN-LAST:event_clearQueryFilter

    private void updateQueryFilter()
    {
	String text = QueryField.getText();
	if (text.length() == 0)
	{
	    clearQueryFilter();
	}
	else
	{
	    ClearButton.setEnabled(true);
	    sifter.setQFilter(text);
	}
    }

    private void clearQueryFilter()
    {
	ClearButton.setEnabled(false);
	sifter.setQFilter(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JTextField QueryField;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
