/*
 * EquipmentTab.java
 *
 * Created on August 5, 2008, 7:34 PM
 */

package pcgen.gui.proto.tabs;

/**
 *
 * @author  Connor Petty <cpmeister@users.sourceforge.net>
 */
public class EquipmentTab extends javax.swing.JPanel {
    
    /** Creates new form EquipmentTab */
    public EquipmentTab() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        flippingSplitPane1 = new pcgen.gui.tools.FlippingSplitPane();
        flippingSplitPane2 = new pcgen.gui.tools.FlippingSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTreeViewSelectionPane1 = new pcgen.gui.util.JTreeViewSelectionPane();
        filteredTreeViewPanel1 = new pcgen.gui.filter.FilteredTreeViewPanel();
        filteredTreeViewPanel2 = new pcgen.gui.filter.FilteredTreeViewPanel();
        chooserPane1 = new pcgen.gui.tools.ChooserPane();

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Total Value:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Gold:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jTextField1.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 6);
        jPanel1.add(jTextField1, gridBagConstraints);

        jCheckBox2.setText("Ignore Cost");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jCheckBox2, gridBagConstraints);
        jPanel1.add(jLabel7, new java.awt.GridBagConstraints());

        jCheckBox3.setText("Allow Debt");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, jCheckBox2, org.jdesktop.beansbinding.ELProperty.create("${!selected}"), jCheckBox3, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jCheckBox3, gridBagConstraints);
        jPanel1.add(jLabel8, new java.awt.GridBagConstraints());

        jLabel4.setText("Buy Percentage:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel4, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, jCheckBox2, org.jdesktop.beansbinding.ELProperty.create("${!selected}"), jComboBox1, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 6);
        jPanel1.add(jComboBox1, gridBagConstraints);
        jPanel1.add(jLabel9, new java.awt.GridBagConstraints());

        jLabel5.setText("Sell Percentage:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jLabel5, gridBagConstraints);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, jCheckBox2, org.jdesktop.beansbinding.ELProperty.create("${!selected}"), jComboBox2, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 6);
        jPanel1.add(jComboBox2, gridBagConstraints);

        jCheckBox1.setText("Auto Resize");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jCheckBox1, gridBagConstraints);

        flippingSplitPane1.setDividerSize(7);
        flippingSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        flippingSplitPane1.setOneTouchExpandable(true);

        flippingSplitPane2.setDividerSize(7);
        flippingSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        flippingSplitPane2.setOneTouchExpandable(true);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setText("Equip Set:");
        jPanel3.add(jLabel6);

        jTextField2.setText("jTextField2");
        jPanel3.add(jTextField2);

        jButton1.setText("Add");
        jPanel3.add(jButton1);

        jButton2.setText("Remove");
        jPanel3.add(jButton2);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);
        jPanel2.add(jTreeViewSelectionPane1, java.awt.BorderLayout.CENTER);

        flippingSplitPane2.setTopComponent(jPanel2);
        flippingSplitPane2.setRightComponent(filteredTreeViewPanel1);

        flippingSplitPane1.setLeftComponent(flippingSplitPane2);
        flippingSplitPane1.setRightComponent(filteredTreeViewPanel2);

        setLayout(new java.awt.BorderLayout());

        chooserPane1.setPrimaryChooserComponent(flippingSplitPane1);
        chooserPane1.setSecondaryChooserComponent(jPanel1);
        add(chooserPane1, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pcgen.gui.tools.ChooserPane chooserPane1;
    private pcgen.gui.filter.FilteredTreeViewPanel filteredTreeViewPanel1;
    private pcgen.gui.filter.FilteredTreeViewPanel filteredTreeViewPanel2;
    private pcgen.gui.tools.FlippingSplitPane flippingSplitPane1;
    private pcgen.gui.tools.FlippingSplitPane flippingSplitPane2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private pcgen.gui.util.JTreeViewSelectionPane jTreeViewSelectionPane1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    
}
