<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
	$IP = MW_INSTALL_PATH;
} else {
	$IP = dirname( __FILE__ );
}

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

require_once( "$IP/includes/DefaultSettings.php" );

# If PHP's memory limit is very low, some operations may fail.
# ini_set( 'memory_limit', '20M' );

if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
}
## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename         = "PCGen Wiki";
$wgLogo = "skins/common/images/pcgenlogo.png";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "";
$wgScriptExtension  = ".php";

$wgArticlePath      = "/$1";
$wgUsePathInfo      = false;

## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO

$wgEmergencyContact =  "wiki@pcgen.org";
$wgPasswordSender   =  "wiki@pcgen.org";
$wgNoReplyAddress	= false;
$wgEmailConfirmToEdit= true;

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

#$wgUsersNotifiedOnAllChanges  

$wgEnotifWatchlist = true;
# Declare this twice so it works for all versions
$wgUsersNotifiedOnAllChanges =
$wgUsersNotifedOnAllChanges = array( 'LegacyKing', 'James', 'Karianna' );
# Groups don't seem to work

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = "localhost";
$wgDBname           = "pcgen1_pcgenwikidb";
$wgDBuser           = "pcgen1_wiki";
$wgDBpassword       = "PCGENwiki1423";

# MySQL specific settings
$wgDBprefix         = "mw_";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = true;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
# $wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

$wgLocalInterwiki   = strtolower( $wgSitename );

$wgLanguageCode = "en";

$wgSecretKey = "dba05004ae47e6e6c5ade8950cd5d6f59fa74809ae91daa26b5d09aadd226f06";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
$wgDefaultSkin = 'monobook';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
# $wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";
# $wgRightsCode = ""; # Not yet used

$wgDiff3 = "/usr/bin/diff3";

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$wgCacheEpoch = max( $wgCacheEpoch, gmdate( 'YmdHis', @filemtime( __FILE__ ) ) );

### Extensions
# Security/permissions settings
# Stop anonymous editing
$wgGroupPermissions['*']['edit']       = false;
$wgGroupPermissions['*']['createtalk'] = false;
$wgGroupPermissions['*']['createpage'] = false;

#Restrict anonymous editing
$wgShowIPinHeader = false;

# Require approval of new accounts
#require_once("$IP/extensions/ConfirmAccount/SpecialConfirmAccount.php");
#$wgAccountRequestMinWords=5;
#$wgConfirmAccountContact = "wikiadmin@pcgen.org";

# Notify new accounts
require_once( "{$IP}/extensions/NewUserNotif/NewUserNotif.php" );
$wgNewUserNotifTargets = array( 'James', 'LegacyKing', 'Karianna' );

# Anti spam settings
$wgSpamRegex = "/\<.*style.*?(display|position|overflow|visibility|height)\s*:.*?>/i";


# EXTENSIONS - Added by LK

# Cite - Requested by Tom
require_once("$IP/extensions/Cite/Cite.php");

# Simple Anti Spam
require_once("$IP/extensions/SimpleAntiSpam/SimpleAntiSpam.php");
			
# AntiSpoof
require_once("$IP/extensions/AntiSpoof/AntiSpoof.php");

# Merge & Delete Extension
require_once( "$IP/extensions/UserMerge/UserMerge.php" );
$wgGroupPermissions['bureaucrat']['usermerge'] = true;
 
#optional - default is array( 'sysop' )
$wgUserMergeProtectedGroups = array( 'sysop', 'administrators', 'bureaucrat' );

#Allow ALL users to be merged (by default, the 'sysop' group is unmergable)
#$wgUserMergeProtectedGroups = array();
#Disallow merging of the users in the 'sysop' or 'awesomeusers' groups
$wgUserMergeUnmergeable = array( 'sysop', 'administrators', 'bureaucrat' );

# Extension - AutoWatch - This emails specified users of any new pages
$wgMultiWatchUserIDs = array( 'James', 'LegacyKing', 'Karianna' ); #This is the list of your users' IDs to include in this mailing list
require_once("extensions/AutoWatch/AutoWatch.php");
# 14 = LegacyKing, 

# Extension - ArticleCategory
#require_once("$IP/extensions/ArticleToCategory/articletocategory.php");

# Extension - Restrict Access By Category and Group
#require_once("$IP/extensions/rabcg/rabcg.php");
#$wgWhitelistRead = array('Special:UserLogin');

# Extension - Renameuser
require_once("$IP/extensions/Renameuser/SpecialRenameuser.php");

#
#require_once("$IP/extensions/GroupPermissionsManager/GroupPermissionsManager.php");

$wgGroupPermissions['sysop']['passwordreset']   = true;
require_once( "$IP/extensions/PasswordReset/PasswordReset.php" );

$wgShowExceptionDetails = true;

