/*
 * FilteredSelectionDialog.java
 *
 * Created on July 23, 2008, 3:43 PM
 */
package pcgen.gui.tools;

import java.util.Hashtable;
import javax.swing.undo.StateEditable;
import pcgen.gui.facade.CharacterFacade;
import pcgen.gui.filter.FilterableTreeViewModel;

/**
 *
 * @author  Connor Petty <cpmeister@users.sourceforge.net>
 */
public class FilteredSelectionDialog extends javax.swing.JDialog implements StateEditable
{

    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;

    /** Creates new form FilteredSelectionDialog */
    public FilteredSelectionDialog(java.awt.Frame parent)
    {
        super(parent, true);
        initComponents();
    }

    /** Creates new form FilteredSelectionDialog */
    public FilteredSelectionDialog(java.awt.Dialog parent)
    {
        super(parent, true);
        initComponents();
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus()
    {
        return returnStatus;
    }

    public Object getReturnItem()
    {
        return returnItem;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        chooserPane1 = new pcgen.gui.tools.ChooserPane();
        filteredTreeViewSelectionPanel1 = new pcgen.gui.tools.FilteredTreeViewSelectionPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        chooserPane1.setSecondaryChooserComponent(jLabel1);

        filteredTreeViewSelectionPanel1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filteredTreeViewSelectionPanel1ItemStateChanged(evt);
            }
        });
        chooserPane1.setLeftComponent(filteredTreeViewSelectionPanel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(chooserPane1, gridBagConstraints);

        okButton.setText("OK");
        okButton.setEnabled(false);
        okButton.setMaximumSize(new java.awt.Dimension(75, 23));
        okButton.setMinimumSize(new java.awt.Dimension(75, 23));
        okButton.setPreferredSize(new java.awt.Dimension(75, 23));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(okButton, gridBagConstraints);

        cancelButton.setText("Cancel");
        cancelButton.setMaximumSize(new java.awt.Dimension(75, 23));
        cancelButton.setMinimumSize(new java.awt.Dimension(75, 23));
        cancelButton.setPreferredSize(new java.awt.Dimension(75, 23));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(cancelButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void filteredTreeViewSelectionPanel1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filteredTreeViewSelectionPanel1ItemStateChanged
        boolean selected = evt.getStateChange() ==
                java.awt.event.ItemEvent.SELECTED;
        okButton.setEnabled(selected);
        if (selected)
        {
            jLabel1.setText(filteredTreeViewSelectionPanel1.getSelectedItem().toString());
        }
        else
        {
            jLabel1.setText(null);
        }
    }//GEN-LAST:event_filteredTreeViewSelectionPanel1ItemStateChanged

    private void doClose(int retStatus)
    {
        returnStatus = retStatus;
        returnItem = filteredTreeViewSelectionPanel1.getSelectedItem();
        setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private pcgen.gui.tools.ChooserPane chooserPane1;
    private pcgen.gui.tools.FilteredTreeViewSelectionPanel filteredTreeViewSelectionPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;
    private Object returnItem = null;

    public Hashtable<Object, Object> createState(CharacterFacade character,
                                                  FilterableTreeViewModel<?> model)
    {
        return filteredTreeViewSelectionPanel1.createState(character, model);
    }

    public void storeState(Hashtable<Object, Object> state)
    {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void restoreState(Hashtable<?, ?> state)
    {
        filteredTreeViewSelectionPanel1.restoreState(state);
    }

}
