/*
 * AdvancedSourceSelectionPanel.java
 * Copyright 2009 Connor Petty <cpmeister@users.sourceforge.net>
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 * 
 * Created on Feb 21, 2009, 6:13:50 PM
 */

/*
 * AdvancedSourceSelectionPanel.java
 *
 * Created on Feb 21, 2009, 6:13:50 PM
 */

package pcgen.gui.proto;

/**
 *
 * @author Connor Petty <cpmeister@users.sourceforge.net>
 */
public class AdvancedSourceSelectionPanel extends javax.swing.JPanel {

    /** Creates new form AdvancedSourceSelectionPanel */
    public AdvancedSourceSelectionPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{
		
		filteredTreeViewSelectionPanel1 = new pcgen.gui.tools.FilteredTreeViewSelectionPanel();
		chooserPane1 = new pcgen.gui.tools.ChooserPane();
		
		setLayout(new java.awt.BorderLayout());
		
		chooserPane1.setPrimaryChooserComponent(filteredTreeViewSelectionPanel1);
		add(chooserPane1, java.awt.BorderLayout.CENTER);
	}// </editor-fold>//GEN-END:initComponents


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private pcgen.gui.tools.ChooserPane chooserPane1;
	private pcgen.gui.tools.FilteredTreeViewSelectionPanel filteredTreeViewSelectionPanel1;
	// End of variables declaration//GEN-END:variables

}
