/*
 * SummaryPanel.java
 *
 * Created on August 13, 2008, 3:34 PM
 */

package pcgen.gui.proto;

/**
 *
 * @author  Connor Petty <cpmeister@users.sourceforge.net>
 */
public class SummaryPanel extends javax.swing.JPanel {
    
    /** Creates new form SummaryPanel */
    public SummaryPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
