</div> <!-- div pagebody -->

<div id="pagebar">

    <img src="images/logo.png" border="0" alt="banner" title="Greek goddess Athena"/>
    <div style="clear: both;"></div>
    <h1>Creating RPG Characters has never been easier!</h1>
	<p>PCGen is a free, open-source program that allows you to create, maintain and print RPG characters using sources from Wizards of the Coast, Paizo Publishing and dozens of other publishers. Let us do the math for you!</p>

    <h1>Statistics</h1>
    <p>

<?php

writeStatItems("http://sourceforge.net/export/rss2_projsummary.php?group_id=25576");

?>

    </p>

    <h1>Licensing</h1>
    <p>The PCGen is distributed is distributed under the <a href="http://www.gnu.org/licenses/licenses.html#LGPL">GNU Lesser General Public License</a> (LGPL).</p>
    
    <p>PCGen's data sources are licensed under the <a href="http://www.opengamingfoundation.org/ogl.html" title="Wizards of the Coast's Open Gaming License">Open Gaming License (OGL)</a> 
    	and the <a href="http://paizo.com/paizo/about/communityuse" title="Paizo Publishing, LLC Community Use Policy">Paizo Community Use Policy</a> along with individual agreements with 
    	the various publishers supported; see the <a href="http://wiki.pcgen.org/index.php?title=Data_License">Data License</a> team on our wiki for details.</p>

    <h1>Associations</h1>
    <p>
    <div align="center">
        <a href="http://www.opensource.org/docs/definition.php" title="Certified with the OSI"><img src="images/button_osi.png" width="88" height="31" alt="Certified with the OSI" border="0" /></a>
	<a href="http://sourceforge.net/projects/pcgen" title="Hosted by SourceForge"><img src="http://sflogo.sourceforge.net/sflogo.php?group_id=25576&amp;type=12" width="88" height="31" border="0" alt="Get PCGen :: A RPG Character Generator at SourceForge.net. Fast, secure and Free Open Source software downloads" /></a>
    </div>
    <div align="center">
        <a href="http://www.w3.org/MarkUp/" title="Rendered in XHTML1"><img src="images/button_xhtml.png" width="88" height="31" alt="Rendered in XHTML1" border="0" /></a>
        <a href="http://www.w3.org/Style/CSS/" title="Styled by CSS1/2"><img src="images/button_css.png" width="88" height="31" alt="Styled by CSS1/2" border="0" /></a>
        <br />
    </div>
    <div align="center">
        <a href="http://www.yourkit.com" title="Supported by YourKit"><img src="images/button_yjp.jpg" width="200" height="51" alt="Supported by YourKit" border="0" /></a>
        <br />
    </div>
    </p>

    <h1>Awards</h1>
    <p>
    <div align="center" id="noborder">
        <a href="http://www.enworld.org/ennies/index.php" title="2005 Gold ENnie winner for 'Best Electronic Product'."><img src="images/gold200x200-2005.gif" width="200" alt="2005 Gold ENnie winner for 'Best Electronic Product'." border="0" style="noborder"/></a>
        <br />
    </div>
    <div align="center" id="noborder">
        <a href="http://www.enworld.org/ennies/index.php" title="2003 ENnie nominee for 'Best Resource Fan Site'."><img src="images/bronze200x200-2003.gif" width="200" alt="2003 ENnie nominee for 'Best Resource Fan Site'." border="0" /></a>
        <br />
    </div>
	</p>
	
</div> <!-- div pagebar -->

<br clear="all" />

</body>
</html>
